# Generated by Django 4.2.7 on 2023-12-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
