# Generated by Django 4.2.7 on 2023-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.JSONField(default='{}'),
        ),
    ]
